print("*****************************")
print("*   DEBUG CHECKLIST         *")
print("*****************************")
print("* 1 Read the last line      *")
print("* 2 Find the line number    *")
print("* 3 Check quotes and ()     *")
print("* 4 Check lowercase print   *")
print("* 5 Check leading spaces    *")
print("*****************************")
