print("------------------------")
print("      MINI MART")
print("------------------------")
print("Milk              25")
print("Bread             35")
print("Egg 6 pcs         42")
print("------------------------")
print("Total            102")
print("------------------------")
print("Thank you!")
