print("........................")
print("   TRANSFER SUCCESS")
print("........................")
print("To      : Somchai P.")
print("Bank    : Test Bank")
print("Account : xxx-x-x1234")
print("........................")
print("Amount  : 1,250.00 THB")
print("Fee     : 0.00 THB")
print("........................")
print()
print("Keep this slip as evidence")
