print("############################")
print("#                          #")
print("#     SPACE ADVENTURE      #")
print("#                          #")
print("############################")
print("#   1. New Game            #")
print("#   2. Continue            #")
print("#   3. Exit                #")
print("############################")
print("Press a number to select")
