print("*========================================*")
print("|                                        |")
print("|            CERTIFICATE                 |")
print("|          OF ACHIEVEMENT                |")
print("|                                        |")
print("|         This is given to               |")
print("|                                        |")
print("|            MINT SUKSAN                 |")
print("|                                        |")
print("|      Python Beginner Camp 2026         |")
print("|                                        |")
print("*========================================*")
