print("[ SCREEN 1 ]")
print("+--------------------+")
print("|  INSERT YOUR CARD  |")
print("+--------------------+")
print()
print("[ SCREEN 2 ]")
print("+--------------------+")
print("|  ENTER PIN         |")
print("|  * * * *           |")
print("+--------------------+")
print()
print("[ SCREEN 3 ]")
print("+--------------------+")
print("|  SELECT SERVICE    |")
print("|  1. Withdraw       |")
print("|  2. Balance        |")
print("+--------------------+")
