name = input()
age = int(input())
grade = input()
print("========================")
print("       STUDENT")
print("========================")
print("Name  :", name)
print("Age   :", age)
print("Grade :", grade)
print("========================")
