name = input()
age = int(input())
height = float(input())
city = input()
print("========================")
print("       PROFILE")
print("========================")
print("Name   :", name)
print("Age    :", age)
print("Height :", height)
print("City   :", city)
print("========================")
