customer = input()
drink = int(input())
snack = int(input())
tip = int(input())
total = drink + snack + tip
print("========================")
print("        CAFE")
print("========================")
print("Customer :", customer)
print("Drink    :", drink)
print("Snack    :", snack)
print("Tip      :", tip)
print("Total    :", total)
print("========================")
